# The following libraries must be loaded: 

library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
library(vcfR)
library(adegenet)
library(SNPRelate)
library(pheatmap)
library(ape)
library(ggtree)
library(stringr)
library(Biostrings)
library(plotly)
library(viridis)
